# Generated by Django 2.1 on 2018-08-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='begin date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Room')),
            ],
        ),
    ]
