# Generated by Django 2.1 on 2018-08-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='begin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.IntegerField(),
        ),
    ]
