# Generated by Django 2.1 on 2018-08-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_auto_20180827_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
